#!/bin/sh

# Colours
red="\033[00;31m"
CYAN="\033[01;36m"
white="\033[00;37m"
WHITE="\033[01;37m"

# Info
CPUMOD=$(cat /proc/cpuinfo | grep -m 1 -w 'model name' | awk -F: '{print $2}')
HOSTNAME=$(uname -n)
KERNEL=$(uname -r)
LINUXVER=$(awk -F "=" '/PRETTY_NAME/ {print $2}' /etc/os-release| sed 's/"//g')
MEMTOTAL=$(cat /proc/meminfo | grep -m 1 -w 'MemTotal' | awk -F: '{print $2}' | sed -e 's/^[[:space:]]*//')
MEMFREE=$(cat /proc/meminfo | grep -m 1 -w 'MemFree' | awk -F: '{print $2}' | sed -e 's/^[[:space:]]*//')
SWAPTOTAL=$(cat /proc/meminfo | grep -m 1 -w 'SwapTotal' | awk -F: '{print $2}' | sed -e 's/^[[:space:]]*//')
SWAPFREE=$(cat /proc/meminfo | grep -m 1 -w 'SwapFree' | awk -F: '{print $2}' | sed -e 's/^[[:space:]]*//')
IPADDR=$( ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
DISKSPACE=$(df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size | tail -n+2)

echo -n "${WHITE}"
/usr/bin/env figlet "${HOSTNAME}"

echo -n "${red}"
echo "Welcome to the n8n Raspberry Pi Server!"
echo
echo "${red}===${WHITE}System Info${red}==="
echo "${CYAN}System Version...: ${white}${LINUXVER}"
echo
echo "${red}===${WHITE}Memory${red}==="
echo -n "${CYAN}Memory Total...: ${white}${MEMTOTAL}  "
echo "${CYAN}Memory Free....: ${white}${MEMFREE}"
echo -n "${CYAN}Swap Total.....: ${white}${SWAPTOTAL}  "
echo "${CYAN}Swap Free......: ${white}${SWAPFREE}"
echo
echo "${red}===${WHITE}Disk Usage${red}==="
echo "${CYAN}Partition  Used  Size"
echo "====================="
echo "${white}${DISKSPACE}"
echo
echo "${red}===${WHITE}Network${red}==="
echo "${CYAN}IP Address.....: ${white}${IPADDR}"
