#!/bin/sh

# Colours
red="\033[00;31m"
CYAN="\033[01;36m"
white="\033[00;37m"
NC="\033[00m"

# Info
NPMVER=$(npm -v)
NODEJSVER=$(node -v)
N8NVER=$(jq -r .version /home/n8n/.nodejs_global/lib/node_modules/n8n/package.json)

echo
echo "${red}===${WHITE}NodeJS Info${red}==="
echo -n "${CYAN}NPM Version....: ${white}${NPMVER}  "
echo "${CYAN}NodeJS Version......: ${white}${NODEJSVER}"
echo
echo "${red}===${WHITE}n8n Info${red}==="
echo "${CYAN}n8n Version....: ${white}${N8NVER}"
echo "${CYAN}n8n Website....: ${white}https://n8n.io"
echo "${CYAN}Documentation..: ${white}https://docs.n8n.io"
echo "${CYAN}Forum..........: ${white}https://community.n8n.io"
echo "${CYAN}Github.........: ${white}https://github.com/n8n-io/n8n"
echo "${CYAN}n8n-pi Website.: ${white}http://n8n-pi.tephlon.xyz"
echo -n "${NC}"
